---
title: "{{< meta pagetitle >}}"
editor: visual
params:
  org_id: 11001065
website:
  title: "Organogramy"
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE, include = FALSE}
library(targets)
library(visNetwork)
library(dplyr)
library(tidyr)
library(ptrr)
library(ggplot2)
library(tidygraph)
library(ggraph)
library(stringr)

ptrr::set_geom_defaults()
ptrr::set_ptrr_ggplot_fonts()
knitr::opts_chunk$set(fig.path = paste0("figures-org/", params$kraj), 
                      warning = FALSE, message = FALSE, echo = FALSE)

source("R/visnetwork.R")
source("R/load-orgchart.R")
```

```{r load}
targets::tar_load(orgdata_graph)
targets::tar_load(urady_tbl)
```

```{r}
urad_zkr <- urady_tbl[urady_tbl$id == params$org_id,"urad_zkratka"][[1]]
urad_nazev <- urady_tbl[urady_tbl$id == params$org_id,"urad_nazev"][[1]]
```

```{r}
layout_code <- if_else(urad_zkr == "ÚP ČR", "layout_with_kk", "layout_nicely")
```

[←zpět na seznam](index.html)

::: callout-note
### Legenda označení útvarů {#legenda-označení-útvarů}

::: legend-box
[Analýzy a evaluace]{.lg .anal} [Hodnocení]{.lg .hodnoc}, dopad [Výzkum]{.lg .vyzk} [Monitoring]{.lg .monit} [Strategie, politiky, koncepce]{.lg .strat} [Statistika]{.lg .stat} [Ostatní]{.lg}
:::
:::

Počet lidí zobrazený při najetí na bod útvaru zahrnuje lidi pracující přímo v útvaru a všech jeho podřízených útvarech.

```{r}
make_org_visnetwork(orgdata_graph, urad_zkr, layout_code)
```

```{r}
make_org_visnetwork(orgdata_graph, urad_zkr)
```

```{r}
targets::tar_load(orgdata_date)
```

Stav k `r orgdata_date`
