project:
  type: website
  output-dir: docs
  resources: ["/orgs/site_libs", "/orgs/*.html", "/orgs/styles.css", "/data-export/app_sims/*", "/data-export/app_jobs.json"]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



